[package]
name = "dragark"
version = "1.0.0"
cairo-version = "=2.8.4"

[cairo]
sierra-replace-ids = true

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["dojo::world::world_contract::world"]

[dependencies]
starknet = "2.8.4"
dojo = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.0.1" }

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.0.1" }

[features]
default = []

[profile.dev]
[profile.release]
